version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html/example.com
      - ./ssl/certs/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./letsencrypt/etc/live/rev3.tk/fullchain.pem:/etc/letsencrypt/live/example.com/fullchain.pem
      - ./letsencrypt/etc/live/rev3.tk/privkey.pem:/etc/letsencrypt/live/example.com/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
